### ISSUE TITLE
[BUG] CI is broken

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#6]
### Expected behavior

CI should not error out (whether tests pass or fail)

### Actual behavior

Cryptic CI error messages

### Reproduction steps

Do anything

### Please provide the following
*   Java Version: ??
*   exist-db version: ??
*   pr-app version: ??
*   OS version: ??

**Comment by djbpitt** [comment]
One of the four CI error reports reads:

```
/home/runner/work/pr-app/pr-app/node_modules/mocha/lib/runner.js:965
41
    throw err;
42
    ^
43

44
SyntaxError: Unexpected token < in JSON at position 0
45
    at JSON.parse (<anonymous>)
46
    at IncomingMessage.<anonymous> (/home/runner/work/pr-app/pr-app/test/xqs/xqSuite.js:22:26)
47
    at IncomingMessage.emit (events.js:326:22)
48
    at endReadableNT (_stream_readable.js:1241:12)
49
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
50
npm ERR! Test failed.  See above for more details.
51
Error: Process completed with exit code 1.
```

Duncan (developer of Yeoman) writes:

> The error indicates that there is an illegal character in a generated json, but on first glance there isn't.
